<a href="https://colab.research.google.com/github/JainamChoudhari16/NumPy/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## ***1D Array:***

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.ndim #printing dimension of the array

1

In [5]:
a[0] #printing element using array indexing

1

In [6]:
type(a)

numpy.ndarray

In [7]:
a[0:-1:3] #printing sub-array using array slicing

array([1, 4])

In [8]:
a[3]

4

In [9]:
a.sum() #printing sum of all elements

15

In [10]:
a[3] = 50 #changing element of an array

In [11]:
a[1:5] = 7,8,9,10 #changing a part of array at a time using slicing

In [12]:
a

array([ 1,  7,  8,  9, 10])

In [13]:
#Mathematical functions:
a1 = np.array([1,2,3,4,5])
a2 = np.array([4,9,16,25,36])
print(np.add(a1,a2)) #adding arrays a1 & a2
print(np.subtract(a2,a1)) #subtracting arrays a1 & a2
print(np.sqrt(a1))
print(np.sqrt(a2))

[ 5 11 19 29 41]
[ 3  7 13 21 31]
[1.         1.41421356 1.73205081 2.         2.23606798]
[2. 3. 4. 5. 6.]


## ***2D Array: It is always collection of 1D arrays.***

In [14]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [15]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
b.ndim

2

In [17]:
b[1] #printing specific row

array([5, 6, 7, 8])

In [18]:
b[:,0] #printing specific column

array([1, 5, 9])

In [19]:
b[1,1] #printing an element using rows and columns

6

In [20]:
b[1,1].ndim

0

In [21]:
b[1].ndim

1

In [22]:
b.sum() #printing sum of all elements

78

In [23]:
b[:2,1:3] #printing specific sub-arrays using rows and columns slicing

array([[2, 3],
       [6, 7]])

In [24]:
b[1][1] #printing element using only row slicing

6

In [25]:
b[1][1:4] #printing sub-array using only row slicing

array([6, 7, 8])

In [26]:
b[:,1][1] #printing element using only column slicing

6

In [27]:
b[:,1][1:4] #printing sub-array using only column slicing

array([ 6, 10])

In [28]:
b[::2,::3] #printing corner elements of 2D array using row & column slicing

array([[ 1,  4],
       [ 9, 12]])

In [29]:
b.shape #printing no. of rows & columns
#Everytime the product of outcome will be equal to no. of elements in the whole array i.e 3*4=12

(3, 4)

In [30]:
b.ravel() #printing all elements in 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
b.size #printing number of elements in the 2D array

12

In [32]:
len(b) #printing number of 1D arrays in 2D array

3

In [33]:
#Reshape converts an N-D array into another N-D array. Eg: 2D-->4D,3D-->2D,etc.
#for 2D array size=rows*columns
b.reshape(6,2) #Here the number of elements remains same but the size of rows & columns changes

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
#np.arange(stop) by default start = 0 & step = 1
np.arange(8) #creates array of size 8 by default starts from 0 to n-1 where n is size of array specified

array([0, 1, 2, 3, 4, 5, 6, 7])

In [35]:
#np.arange(start,stop,step)
np.arange(8,16,2)

array([ 8, 10, 12, 14])

In [36]:
#creating 2D array with 3 rows and 5 columns of 15 elements
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## ***3D Array: It is always collection of 2D arrays.***

In [37]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [38]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
c.ndim

3

In [40]:
c[0] #printing 1st 2D array from 3D array.

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
c[0][0] #printing 1st 1D array of 1st 2D array.

array([1, 2, 3])

In [42]:
c[1][0][1] #printing specific element using indexing

8

In [43]:
c[1][:,1:3] #printing specific sub-array using slicing but following sub-array is 2D array because of 2 square brackets

array([[ 8,  9],
       [11, 12]])

In [44]:
#printing specifi sub-array using slicing but in 3D array
c[1:2,:1] #1:2 is for slicing 3D array & :1 is for slicing 2D array in that particular 3D array.

array([[[7, 8, 9]]])

In [45]:
c[1:2,:,::2] #printing corners elements of 2nd 2D array
#Here, first 1:2 is for selecting 2nd 2D array then in that : is selecting both the rows of that 2D array & ::2 is for selecting first and last column of that 2D array.

array([[[ 7,  9],
        [10, 12]]])

In [46]:
#printing first and last element of 2nd 1D array of both the 2D arrays. i.e. [[[4.6],[10,12]]]
c[:,1:2,::2]

array([[[ 4,  6]],

       [[10, 12]]])

In [47]:
c.sum()

78

In [48]:
c.shape #prints shape of the array
#Here 1st 2 is for no. of 2D arrays in 3D array, next 2 is for no. of rows in each 2D array and last 3 is for no. of columns in each 2D array
#Everytime the product of outcome will be equal to no. of elements in the whole array i.e 2*2*3 = 12

(2, 2, 3)

In [49]:
c.reshape(3,2,2) #changing the shape of the 3D array
#for 3D array reshape(no. of 2D arrays,no. of rows of 2D arrays,no. of columns of 2D arrays)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [50]:
#Creating a 3D array using arange and reshape functions.
d = np.arange(1,46).reshape(5,3,3)
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]]])

In [51]:
d.reshape(9,5) #converting a 3D array into 2D array with 9 rows and 5 columns.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

## ***Statistical Functions:***

In [52]:
#Statistical Functions on 1D array:
a3 = [76, 78, 81, 66, 85]
print(np.mean(a3)) #printing mean of values in array a3
print(np.median(a3)) #printing meadian of values in array a3
print(np.min(a3)) #printing minimum of values in array a3
print(np.max(a3)) #printing maximum of values in array a3

77.2
78.0
66
85


In [53]:
# compute the standard deviation of marks
std_deviation = np.std(a3)
print(std_deviation)

6.368673331236263


In [54]:
#Statistical Functions on ND array:
array1 = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [55]:
# compute median along horizontal axis(rows)
result1 = np.median(array1, axis=1)
print("Median along rows :", result1)

Median along rows : [ 4. 10. 16.]


In [56]:
# compute median along vertical axis(columns)
result2 = np.median(array1, axis=0)
print("Median along columns:", result2)

Median along columns: [ 8. 10. 12.]


In [57]:
# compute median of entire array
result3 = np.median(array1)
print("Median of entire array:", result3)

Median of entire array: 10.0


In [58]:
# calculate the mean of the entire array
result1 = np.mean(array1)
print("Entire Array:",result1)

Entire Array: 10.0


In [59]:
# calculate the mean along columns (axis=0)
result2 = np.mean(array1, axis=0)
print("Along columns:",result2)

Along columns: [ 8. 10. 12.]


In [60]:
# calculate the mean along  rows(axis=1)
result3 = np.mean(array1, axis=1)
print("Along rows :",result3)

Along rows : [ 4. 10. 16.]


In [61]:
# compute standard deviation along rows
result1 = np.std(array1, axis=1)
print("Standard deviation along horizontal axis:", result1)

Standard deviation along horizontal axis: [1.63299316 1.63299316 1.63299316]


In [62]:
# compute standard deviation along columns
result2 = np.std(array1, axis=0)
print("Standard deviation  along vertical axis:", result2)

Standard deviation  along vertical axis: [4.89897949 4.89897949 4.89897949]


In [63]:
# compute standard deviation of entire array
result3 = np.std(array1)
print("Standard deviation of entire array:", result3)

Standard deviation of entire array: 5.163977794943222


## ***Numpy Array Input/Output Functions:***

In [64]:
array1 = np.array([[1, 3, 5], [2, 4, 6]])

In [65]:
# save the array to a text file
np.savetxt('data.txt', array1)

In [66]:
# load the data from the text file
loaded_data = np.loadtxt('/content/data.txt')

In [67]:
# print the loaded data
print(loaded_data)

[[1. 3. 5.]
 [2. 4. 6.]]


## ***NumPy Comparison Operators***

In [68]:
arr1 = np.array([9,12,21])
arr2 = np.array([21,12,9])

In [69]:
# less than operator
result1 = arr1 < arr2
print("array1 < array2:",result1)    # Output: [ True False False]

array1 < array2: [ True False False]


In [70]:
# greater than operator
result2 = arr1 > arr2
print("array1 > array2:",result2)    # Output: [False False  True]

array1 > array2: [False False  True]


In [71]:
# equal to operator
result3 = arr1 == arr2
print("array1 == array2:",result3)    # Output: [False  True False]

array1 == array2: [False  True False]


In [72]:
# use of less()
result = np.less(arr1, arr2)
print("Using less():",result)    # Output: [ True False False]

Using less(): [ True False False]


In [73]:
# use of less_equal()
result = np.less_equal(arr1, arr2)
print("Using less_equal():",result)     # Output: [ True  True False]

Using less_equal(): [ True  True False]


In [74]:
# use of greater()
result = np.greater(arr1, arr2)
print("Using greater():",result)    # Output: [False False  True]

Using greater(): [False False  True]


In [75]:
# use of greater_equal()
result = np.greater_equal(arr1, arr2)
print("Using greater_equal():",result)    # Output: [False  True  True]

Using greater_equal(): [False  True  True]


In [76]:
# use of equal()
result = np.equal(arr1, arr2)
print("Using equal():",result)    # Output: [False  True False]

Using equal(): [False  True False]


In [77]:
# use of not_equal()
result = np.not_equal(arr1, arr2)
print("Using not_equal():",result)    # Output: [ True False  True]

Using not_equal(): [ True False  True]


## ***NumPy Logical Operations***

In [78]:
x1 = np.array([True, False, True])
x2 = np.array([False, False, True])

In [79]:
# Logical AND
print(np.logical_and(x1, x2)) # Output: [False False  True]

[False False  True]


In [80]:
# Logical OR
print(np.logical_or(x1, x2)) # Output: [ True False  True]

[ True False  True]


In [81]:
# Logical NOT
print(np.logical_not(x1)) # Output: [False  True False]

[False  True False]


## ***Converting Angles into Radians and Degrees***

In [82]:
# define an angle in radians
angle =  1.57079633
print("Initial angle in radian:", angle)

Initial angle in radian: 1.57079633


In [83]:
# convert the angle to degrees
angle_degree = np.degrees(angle)
print("Angle in degrees:", angle_degree)

Angle in degrees: 90.0000001836389


In [84]:
# convert the angle back to radians
angle_radian = np.radians(angle_degree)
print("Angle in radians (after conversion):", angle_radian)

Angle in radians (after conversion): 1.57079633


## ***Rounding Functions***

In [85]:
numbers = np.array([1.23956, 2.34567, 3.45378, 4.56789])

In [86]:
# round the array to two decimal places
rounded_array = np.round(numbers, 2)
print(rounded_array)

[1.24 2.35 3.45 4.57]


In [87]:
print("Array after floor():", np.floor(numbers))

Array after floor(): [1. 2. 3. 4.]


In [88]:
print("Array after ceil():", np.ceil(numbers))

Array after ceil(): [2. 3. 4. 5.]


## ***Numpy String Functions***

In [89]:
array1 = np.array(['iPhone: ', 'price: '])
array2 = np.array(['15', '$900'])
# perform element-wise array string concatenation
result = np.char.add(array1, array2)
print(result)

['iPhone: 15' 'price: $900']


In [90]:
array3 = np.array(['a', 'b', 'c'])
#  repeat each element in array1 two times
result = np.char.multiply(array3, 2)
print(result)

['aa' 'bb' 'cc']


In [91]:
# capitalize the first letter of each string in array1
result = np.char.capitalize(array3)
print(result)

['A' 'B' 'C']


In [92]:
array4 = np.array(['nEpalI', 'AmeriCAN', 'CaNadIan'])
# convert all string elements to uppercase
result1 = np.char.upper(array4)
# convert all string elements to lowercase
result2 = np.char.lower(array4)
print("To Uppercase: ",result1)
print("To Lowercase: ",result2)

To Uppercase:  ['NEPALI' 'AMERICAN' 'CANADIAN']
To Lowercase:  ['nepali' 'american' 'canadian']


In [93]:
# join the strings in the array using a dash as the delimiter
result = np.char.join('-', array4)
print(result)

['n-E-p-a-l-I' 'A-m-e-r-i-C-A-N' 'C-a-N-a-d-I-a-n']


In [94]:
array5 = np.array(['C', 'Python', 'Swift'])
array6 = np.array(['C++', 'Python', 'Java'])
# check if each element of the arrays is equal
result = np.char.equal(array5, array6)
print(result)

[False  True False]
